name: refactoring-CI/CD

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Test
        run: npm run test

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY}}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          script: |
            cd refectoring-BE
            npm ci
            npm run build
            pm2 restart 0
